[WIP] Adds unbind API
flix-tech/MFBBinding pull request #5
Opened 2017-04-24 11:06 UTC by nikolaykasyanov

2017-04-24 13:00 UTC, nikolaykasyanov commented on Tests/MFBBindingTests.m
> +- (void)test_unbindAll_RemovesMatchingBinding
We also need a test to verify that both getter & setter bindings are destroyed.

2017-04-24 13:07 UTC, nikolaykasyanov commented on Tests/MFBBindingTests.m
> +- (void)test_unbindAll_RemovesMatchingBinding
Done.

2017-04-25 08:48 UTC, nikolaykasyanov commented
Found a blocker, fix incoming.

2017-04-25 09:21 UTC, nikolaykasyanov commented
@tarbayev ready for review.

2017-04-28 13:51 UTC, nikolaykasyanov commented
@tarbayev it'd be great to have a review.

2017-04-28 15:26 UTC, tarbayev requested changes

2017-04-28 15:26 UTC, tarbayev commented on Sources/MFBBinding.h
> +- (void)mfb_unbindAll:(NSString *)binding;
I'd call it `mfb_unbind:` same as in Cocoa Bindings. Also object supposed to have a single "setter" binding, thus `...All` suffix does not make sense. Not sure what should happen on attempt to bind same property (i.e. set up setter binding) multiple times: assert fired or binding overridden.

2017-04-28 15:26 UTC, tarbayev commented on Sources/MFBBinding.m
> +{
I guess, we have to unbind only "setter" bindings here (same as Cocoa Bindings do), as object should not unsubscribe its observers, observers should unsubscribe themselves (using `mfb_unbind` ~~All~~`:`).

2017-04-28 15:33 UTC, nikolaykasyanov commented on Sources/MFBBinding.h
> +- (void)mfb_unbindAll:(NSString *)binding;
Fair enough, fixed.

2017-04-28 15:34 UTC, nikolaykasyanov commented on Sources/MFBBinding.m
> +{
True that. Fixed.

2017-04-28 16:16 UTC, tarbayev requested changes

2017-04-28 16:16 UTC, tarbayev commented on Sources/MFBBinding.m
> +{
Also `MFBBindingStore` is not appropriate for setter bindings as we need to override existing bindings.

2017-05-01 00:58 UTC, nikolaykasyanov commented on Sources/MFBBinding.m
> +{
I'd expect that to be out of scope of this PR.

2017-05-02 07:36 UTC, tarbayev approved these changes

2017-05-02 08:21 UTC, merged